### PR TITLE
added 320px styles to hero

### PR DESCRIPTION
**Pull request by laurencun**
[Trello ticket](https://trello.com/c/ay3TGqF1/61-mobile-hero)

### CODE REVIEW

**Comment by lauramoon** [comment]
Need 64px padding on top and 20px either side.
hero

**Comment by laurencun** [comment]
Okay, ready to be reviewed again!

**Comment by lauramoon** [comment]
At exactly 320 px width, the left padding is not showing up as the full 20px. Is it being overridden by the 300px width in the @ media screen section? Does that 300px width need to be removed?

**Comment by laurencun** [comment]
Ready for another review. I adjusted the hero-wrapper to 100%. However, the margin is still a little past the view port due to the width of the h1 at 280px. Let me know if you have other suggestions or think this looks good as is.

**Comment by lauramoon** [comment]
I think that's fine for under 320px.

**Review by lauramoon — APPROVED** [review]

**Pull request merged**
