### PR TITLE
first draft how it works section

### PR DESCRIPTION
**Pull request by lauramoon**

### CODE REVIEW

**Comment by laurencun** [comment]
- Create 18px space between h2 and p
- Need 14px between h3 and p below it
- Need 92px space on left and right of images

**Comment by laurencun** [comment]
nice work. I'll move this ticket over for design/team review.

**Comment by laurencun** [comment]
After comparing with the spec page on figma, it looks like these are the changes needed:
-create 20px between h2 and p at top
-change the space below how it works header from 64 to 29px
-font for h3 should be at 20px
That should be good. Let me know if you have questions or need help.

**Comment by lauramoon** [comment]
I'm seeing 64px/4rem as the space under the heading.
howitworks

**Comment by laurencun** [comment]
Oh, you're right! I'm not sure where I saw that 29 but at a second glance, the spacing there is fine.

**Comment by laurencun** [comment]
looks good to me. Let's pass it to the design/team review section.

**Pull request merged**
