### PR TITLE
make svgs objects in about section

### PR DESCRIPTION
**Pull request by lauramoon**

### CODE REVIEW

**Review by laurencun — CHANGES_REQUESTED** [review]
When I open the netlify preview in safari, the svg's disappear around 730px. I remember Juliette suggested using inline svg's instead of having them as the image source attribute. Does that make sense?

**Comment by lauramoon** [comment]
I thought I made them objects as you described in the card - there shouldn't be any img tags in the about section at all.  Are you seeing something different? Or are you talking about the how it works section? I haven't changed anything there.

**Comment by laurencun** [comment]
Doesn't look like the switch from images to objects is fully fixing it. I would maybe ask Juilette about her suggestion. I've never added svg files inline, so I'm not sure how to do that. 
This is a screen shot of the preview in chrome vs safari on the right. 

Screen Shot 2021-04-29 at 3 42 21 PM

**Review by laurencun — APPROVED** [review]
You got it! I think that's it. Nice job.

**Comment by lauramoon** [comment]
Wait, I haven't changed this one. This link in the Slack DM was for this pull request: https://github.com/sarahlillian/milkweed/pull/48, which takes a different approach to trying to solve the issue.  (Sorry I wasn't clear.)

**Comment by lauramoon** [comment]
Wait, I haven't changed

**Comment by lauramoon** [comment]
Safari mobile issue fixed in #48; these changes unnecessary.

**Pull request closed without merging**
