### PR TITLE
added contact us section and styling

### PR DESCRIPTION
**Pull request by laurencun**
[trello ticket](https://trello.com/c/ENmOqhSq/65-mobile-contact-us-section)

### CODE REVIEW

**Review by lauramoon — CHANGES_REQUESTED** [review]
The word 'contact' should not be in all caps. This applies to the button in the header as well.

**Comment by laurencun** [comment]
Oh, nice catch. Should be fixed now.

**Review by lauramoon — APPROVED** [review]
Looks great

**Comment by lauramoon** [comment]
Something's off with the contact text (too wide), and the footer text is misplaced. Maybe the contact and footer weren't merged properly?
contact

**Pull request closed without merging**
