### PR TITLE
Resources padding 320

### PR DESCRIPTION
**Pull request by lauramoon**
fix padding above resources section @720 and smaller

### CODE REVIEW

**Comment by lauramoon** [comment]
It looks like my formatter made a bunch of spacing changes to my local copy that got included as separate commits. I'm pretty sure there is no actual change to the code other than the one change to the padding above the resources section.

**Comment by lauramoon** [comment]
Latest commit is for the other Trello card, so this pull request covers both Trello cards related to the Resource section.

**Review by laurencun — CHANGES_REQUESTED** [review]
The top padding is looking good. I'll move that trello ticket to design review. 
Could you double-check the width of the resource content div? I'm seeing width at 266px. If you add min-width: 280px @320 that seems to do the trick.

**Comment by lauramoon** [comment]
Thanks, Lauren. I'm thinking we want to let the cards get smaller at < 320px (might want to get Joseph's opinion), but I took out a bit adjusting the margin, and I think the card borders should now be at exactly 280px width at 320px screen now.

**Review by laurencun — APPROVED** [review]
Ok! Passing off to Joseph for final review.

**Pull request merged**
