### PR TITLE
Hero padding and new svgs

### PR DESCRIPTION
**Pull request by laurencun**
I added the new svg's for the logo and hero images. 
As far as the padding between the hero and about section, it's looking different on my end than the photo Joseph included on the Trello [ticket](https://trello.com/c/6Muj26tI/112-space-between-the-hero-and-about-section).
Could you check that it's looking the same as this screenshot at 1322px on the netlify preview?

Screen Shot 2021-04-22 at 10 16 59 AM

### CODE REVIEW

**Comment by lauramoon** [comment]
I am seeing some weirdness right around 1330-1350 on the live site - the space gets quite small and then jumps bigger again.

**Comment by laurencun** [comment]
Ah, okay. I couldn't see it with the chrome inspector tool open. I made some adjustments to the background image height so there's a little more space there now. Let me know if you can see the difference.

**Comment by lauramoon** [comment]
At 1334px, the hero image is still coming way down into the top of the about section, as I see it in Firefox. I'm guessing the hero wrapper may need to be set to grow at the image grows? I can fiddle with it next week if you don't want to  now.

Also, I'm not seeing the padding around the resources section in the preview here, but it is on the live site. I imagine it will return when you resolve the merge conflicts?

**Review by lauramoon — APPROVED** [review]
Looking good!

**Pull request merged**
