### PR TITLE
updated contact-us using figma spec

### PR DESCRIPTION
**Pull request by laurencun**
[trello ticket](https://trello.com/c/ENmOqhSq/65-mobile-contact-us-section)

### CODE REVIEW

**Comment by lauramoon** [comment]
Looks good now. Should the background color be the same as the background color for the resource divs?

**Review by lauramoon — APPROVED** [review]
I'll let Joseph decide if the background color should be different.

**Comment by lauramoon** [comment]
The button is still not centered.

**Comment by laurencun** [comment]
Hmm.. try again now.

**Comment by lauramoon** [comment]
The button is only going to 260px where it should be 280px (same as <a>) at screen width 320px. Does it need to inherit width?
button

**Comment by laurencun** [comment]
The button's edges are a little outside the content box, but it seems centered to me now and it's back to 280px wide. Let me know if that looks better to you.

**Comment by lauramoon** [comment]
Still didn't seem quite right. Tried my hand at it, created a new pull request, see what you think.

**Pull request merged**
