### PR TITLE
adjusted hero content section width

### PR DESCRIPTION
**Pull request by laurencun**
horizontal scroll was caused by hero content section.

### CODE REVIEW

**Comment by laurencun** [comment]
[ticket](https://trello.com/c/IpzDyA1o/137-320-horizontal-scroll)

**Comment by lauramoon** [comment]
I'm still seeing the scroll bar at less than 479px screen width. I tried adjusting the css a bit with no success. Next step I would try moving the hero-img div outside the hero-content div. Let me know if you want me to play with it a bit more.

**Comment by lauramoon** [comment]
Scroll bar is gone! Nice! (Until < 300px width, which seems fine to me).

But I'm seeing a white stripe on the left and right of the image; the design shows the image going to the very edge as it disappears off screen.

image-edge-stripe

**Comment by laurencun** [comment]
I see. Instead of setting overflow hidden on the hero image, I set overflow hidden on the hero wrapper and that seems to do trick.

**Review by lauramoon — APPROVED** [review]
Looks great!

**Pull request merged**
