### PR TITLE
new file structure for cms

### PR DESCRIPTION
**Pull request by laurencun**
Updated file structure to be compatible with CMS. Once merged, we can map fields to edit on the admin side.

### CODE REVIEW

**Comment by laurencun** [comment]
Seems like the Netlify preview isn't showing up correctly, but if you open the branch locally everything is good.

**Comment by lauramoon** [comment]
I got this working locally and it looks great. I'm concerned that the netlify preview doesn't work - I'm wondering if something needs to be configured somewhere to get it to compile properly?

**Comment by lauramoon** [comment]
It also seems to be missing the favicon when I view locally.

**Comment by lauramoon** [comment]
Looks great! I'm wondering if the .jekyll-cache and .vscode folders are needed or if they should be in a .gitignore?

**Comment by laurencun** [comment]
Good point.  I just added them to a .gitignore file. If everything else looks okay, I'll request a review from Joseph as well before merging.

**Comment by lauramoon** [comment]
It looks like those folders are still in the branch. Do they need a '/' in front of the folder name in the gitignore text? (I'm on my phone, not entirely sure I'm seeing things correctly)

**Pull request merged**
