### PR TITLE
header padding and shadow adjustments

### PR DESCRIPTION
**Pull request by laurencun**
[ticket](https://trello.com/c/WHYfNIti/89-320-1440-header)

### CODE REVIEW

**Comment by lauramoon** [comment]
Maybe you just haven't gotten to this, but button should be orange at >= 721px and a simple link at smaller screen sizes. I like the shadow!

**Comment by laurencun** [comment]
Thanks for the catch! I totally forgot to update that. Give it a look now.

**Comment by lauramoon** [comment]
Looks great! Will move the card to design review.

**Review by lauramoon — APPROVED** [review]

**Review by lauramoon — CHANGES_REQUESTED** [review]
The orange button is showing on hover at smaller sizes. And the "press" distance will need to be adjusted to 6px like the other button.

**Pull request merged**
