### PR TITLE
first draft of about section

### PR DESCRIPTION
**Pull request by lauramoon**

### CODE REVIEW

**Comment by laurencun** [comment]
-First heading should say ‘Chicago Needs Natural Habitat’
-h1 is 32px; should be 30px => 1.875em 
-add 18px spacing between h1 and p
-spacing on left and right of about section is 16px; should be at 18px

**Comment by laurencun** [comment]
perfect! looks good to me. I'll move this trello ticket to design/team review.

**Comment by lauramoon** [comment]
Adjusted to 20px per Joseph's design review.

**Comment by laurencun** [comment]
I think you're running into the same problem I was with the margins being a little outside of the view port. 

You have 20px margins for each about-content div, but the width of the about-content or about-content-wrapper might be at more than 100%.

I've found that you can fix this by changing the about-content width to inherit.

Minor adjustments: 
-the spec page shows the 64px between each about-content dv and it's at 32px
-need 32px of space between p and img
-img appears to be slightly to the right, maybe try to re-center it

**Comment by lauramoon** [comment]
Okay, I think it's all fixed. Yay for width: inherit!

**Comment by laurencun** [comment]
you got it. I'll move the ticket over for further review but looks good to me. nice work!

**Pull request merged**
