### PR TITLE
updated contact us text and background color

### PR DESCRIPTION
**Pull request by laurencun**
[ticket](https://trello.com/c/aFnO0oKa/95-320-1440-contact-us)

### CODE REVIEW

**Comment by lauramoon** [comment]
Check the padding above "Contact Us" and below the white button at all sizes. I think Joseph adjusted them from the first spec.

**Comment by laurencun** [comment]
Thanks for the feedback. I took another look and re-adjusted the padding above and below the contact us content at all sizes.

**Review by lauramoon — APPROVED** [review]
Looking good! I'll move it to design review.

**Review by lauramoon — APPROVED** [review]
Looks good!

**Comment by lauramoon** [comment]
Just saw Joseph's comment on Trello - once you make the change, you can move it straight to design approval.

**Comment by lauramoon** [comment]
Looks great to me, I moved it to design review.

**Pull request merged**
