### PR TITLE
first draft resources section

### PR DESCRIPTION
**Pull request by lauramoon**

### CODE REVIEW

**Comment by laurencun** [comment]
- Adjust padding-bottom to 54px on resources header 
- Try to take image size down to 72px
- I believe h4 should be 20px and p should be 16px here 
- Looks like the margin on the left and right of each resource should be at 18px; I think it's at 20px right now.

**Comment by lauramoon** [comment]
I'm confused about your requested changes - I thought my numbers were straight from the Figma diagram. See Slack message if a call would help.

**Comment by laurencun** [comment]
Hi there! Sorry I was out earlier. I figured it might help if I included some screenshots.

1. Adjust padding-bottom to 54px on resources header 

Screen Shot 2021-03-20 at 6 35 41 PM

2. Try to take image size down to 72px

Screen Shot 2021-03-20 at 6 36 21 PM

3. I believe h4 should be 20px and p should be 16px here 

Screen Shot 2021-03-20 at 6 39 28 PM

4. Looks like the margin on the left and right of each resource should be at 18px; I think it's at 20px right now.

Screen Shot 2021-03-20 at 6 40 35 PM

**Comment by lauramoon** [comment]
Okay, this is really weird - I'm seeing different numbers. See, for example, the 80x80 image size from my screenshot below. Are we looking at the same place?

resources

**Comment by laurencun** [comment]
Ah, okay... I see what happened.
I was looking at the @320-Resources-2 section and you are looking at the newer Resources-3 section. 
That was my bad... sorry. So you were on the right track with this the way it is. My apologies!!
Let's move this to design/team review.

**Comment by lauramoon** [comment]
Great! Glad we figured that out. :)

**Pull request merged**
