### PR TITLE
header and hero adjustments

### PR DESCRIPTION
**Pull request by laurencun**

### CODE REVIEW

**Comment by lauramoon** [comment]
The @320 adjustments look good. I'll move those two cards over.

I'm still seeing the text going into the green area @1342 (the transition seems to vary slightly depending on how I view it)

hero1342

**Comment by laurencun** [comment]
I wasn't able to replicate the text going into the green area. However, I made the content width a little smaller. Let me know if that fixes it. Thanks!

**Comment by lauramoon** [comment]
It's weirdly inconsistent for me (maybe it's the browser), I'll go ahead and approve.

**Review by lauramoon — APPROVED** [review]

**Comment by lauramoon** [comment]
Looking good on Firefox now!

**Comment by lauramoon** [comment]
This looks good, moving ticket to design review.

**Comment by lauramoon** [comment]
@laurencun Is this branch needed any more? It looks like all the commits here were included in the CMS pull request merge.

**Comment by lauramoon** [comment]
Hmm, except for the space between the hero title and text is still too large on the live site. Will resolve conflicts here and merge.

**Pull request merged**
