### PR TITLE
Resource butterflies

### PR DESCRIPTION
**Pull request by lauramoon**

### CODE REVIEW

**Review by laurencun — CHANGES_REQUESTED** [review]
Great job! I checked to make sure the svg's are visible in safari and looks good.
The only thing is I'm seeing a horizontal scroll bar from 721px to 1474px.

**Comment by lauramoon** [comment]
Thanks for catching that. I'll try to fix it later today.

**Comment by lauramoon** [comment]
Scrollbar should be gone now.

**Review by laurencun — APPROVED** [review]
Looking good!

**Pull request merged**
